In [11]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.datasets import load_breast_cancer

from sklearn.ensemble import RandomForestClassifier as RF
from sklearn.tree import DecisionTreeClassifier as CART

from KNN import KClasificadorVecinosCercanos as KNN

import time

In [12]:
data = load_breast_cancer()
X, y = data.data, data.target

print(type(X))


<class 'numpy.ndarray'>


In [15]:
# Fetch dataset
dry_bean_dataset = fetch_ucirepo(id=602)

# Data (as pandas dataframes)
X = dry_bean_dataset.data.features
y = dry_bean_dataset.data.targets

# Seleccionar solo las columnas numéricas
X = X.values

# Convertir y a enumerado usando LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Ahora X_numeric tiene solo características numéricas y y es enumerado
print(type(X))
print(y)


<class 'numpy.ndarray'>
[5 5 5 ... 3 3 3]


C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
# fetch dataset 
rice_cammeo_and_osmancik = fetch_ucirepo(id=545) 

# data (as pandas dataframes) 
X = rice_cammeo_and_osmancik.data.features 
y = rice_cammeo_and_osmancik.data.targets
  
# Seleccionar solo las columnas numéricas
X = X.values

# Convertir y a enumerado usando LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Ahora X_numeric tiene solo características numéricas y y es enumerado
print(type(X))
print(y)


<class 'numpy.ndarray'>
[0 0 0 ... 1 1 1]


C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
# Paso 1: Dividir la muestra en entrenamiento (80%) y validación (20%)
X_entrenamiento, X_validacion, y_entrenamiento, y_validacion = train_test_split(X, y, test_size=0.2, random_state=42)

# Paso 2: Utilizar cross-validación para escoger los parámetros relevantes
modelo = KNN()  # Ajusta los parámetros el clasificador elegido

# Crear un objeto de validación cruzada (por ejemplo, con 5 folds)
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Realizar la validación cruzada y obtener los resultados
resultados_cross_val = cross_val_score(modelo, X_entrenamiento, y_entrenamiento, cv=kf)

# Imprimir los resultados de cross-validation
print("Resultados de cross-validation:")
print(resultados_cross_val)
print("Métrica promedio: {:.2f}".format(resultados_cross_val.mean()))


# Crear modelo para medir tiempos
modelo_final = KNN() # Ajusta los parámetros el clasificador elegido

ti_ent= time.time()
modelo_final.fit(X_entrenamiento, y_entrenamiento)
tf_ent= time.time()

# Paso 3: Evaluar el modelo en el conjunto de validación
ti_pred = time.time()
resultados_validacion = modelo_final.score(X_validacion, y_validacion)
tf_pred =time.time()

#Paso 4: Imprimir tiempos

print("Métrica en el conjunto de validación: {:.2f}".format(resultados_validacion))
print("tiempo entrenamiento: {0}".format(tf_ent-ti_ent))
print("tiempo prediccion: {0}".format(tf_pred-ti_pred))


Resultados de cross-validation:
[0.87868852 0.88688525 0.87704918 0.86535304 0.88013136]
Métrica promedio: 0.88
Métrica en el conjunto de validación: 0.88
tiempo entrenamiento: 0.0
tiempo prediccion: 1.4163315296173096


In [19]:
# Paso 1: Dividir la muestra en entrenamiento (80%) y validación (20%)
X_entrenamiento, X_validacion, y_entrenamiento, y_validacion = train_test_split(X, y, test_size=0.2, random_state=42)

# Paso 2: Utilizar cross-validación para escoger los parámetros relevantes
modelo = CART()  # Ajusta los parámetros el clasificador elegido

# Crear un objeto de validación cruzada (por ejemplo, con 5 folds)
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Realizar la validación cruzada y obtener los resultados
resultados_cross_val = cross_val_score(modelo, X_entrenamiento, y_entrenamiento, cv=kf)

# Imprimir los resultados de cross-validation
print("Resultados de cross-validation:")
print(resultados_cross_val)
print("Métrica promedio: {:.2f}".format(resultados_cross_val.mean()))


# Crear modelo para medir tiempos
modelo_final = CART() # Ajusta los parámetros el clasificador elegido

ti_ent= time.time()
modelo_final.fit(X_entrenamiento, y_entrenamiento)
tf_ent= time.time()

# Paso 3: Evaluar el modelo en el conjunto de validación
ti_pred = time.time()
resultados_validacion = modelo_final.score(X_validacion, y_validacion)
tf_pred =time.time()

#Paso 4: Imprimir tiempos

print("Para CART")
print("Métrica en el conjunto de validación: {:.2f}".format(resultados_validacion))
print("tiempo entrenamiento: {0}".format(tf_ent-ti_ent))
print("tiempo prediccion: {0}".format(tf_pred-ti_pred))

Resultados de cross-validation:
[0.86229508 0.88688525 0.90819672 0.863711   0.89819376]
Métrica promedio: 0.88
Para CART
Métrica en el conjunto de validación: 0.88
tiempo entrenamiento: 0.04092693328857422
tiempo prediccion: 0.0009927749633789062


In [20]:
# Paso 1: Dividir la muestra en entrenamiento (80%) y validación (20%)
X_entrenamiento, X_validacion, y_entrenamiento, y_validacion = train_test_split(X, y, test_size=0.2, random_state=42)

# Paso 2: Utilizar cross-validación para escoger los parámetros relevantes
modelo = RF()  # Ajusta los parámetros el clasificador elegido

# Crear un objeto de validación cruzada (por ejemplo, con 5 folds)
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Realizar la validación cruzada y obtener los resultados
resultados_cross_val = cross_val_score(modelo, X_entrenamiento, y_entrenamiento, cv=kf)

# Imprimir los resultados de cross-validation
print("Resultados de cross-validation:")
print(resultados_cross_val)
print("Métrica promedio: {:.2f}".format(resultados_cross_val.mean()))


# Crear modelo para medir tiempos
modelo_final = RF() # Ajusta los parámetros el clasificador elegido

ti_ent= time.time()
modelo_final.fit(X_entrenamiento, y_entrenamiento)
tf_ent= time.time()

# Paso 3: Evaluar el modelo en el conjunto de validación
ti_pred = time.time()
resultados_validacion = modelo_final.score(X_validacion, y_validacion)
tf_pred =time.time()

#Paso 4: Imprimir tiempos

print("Para RF")
print("Métrica en el conjunto de validación: {:.2f}".format(resultados_validacion))
print("tiempo entrenamiento: {0}".format(tf_ent-ti_ent))
print("tiempo prediccion: {0}".format(tf_pred-ti_pred))

Resultados de cross-validation:
[0.92131148 0.9147541  0.93278689 0.91461412 0.93596059]
Métrica promedio: 0.92
Para RF
Métrica en el conjunto de validación: 0.92
tiempo entrenamiento: 0.9996473789215088
tiempo prediccion: 0.011960029602050781
